Master PR
WildCodeSchool/tours-php-2009-project3-taste pull request #29
Opened 2021-01-29 11:31 UTC by axelhamil

2021-01-29 11:37 UTC, Maxime-Auneau approved these changes, later dismissed

2021-02-02 10:45 UTC, Maxime-Auneau submitted a review, later dismissed

2021-02-02 14:08 UTC, RomainClair requested changes
Install documentation incomplete.

2021-02-02 14:31 UTC, Maxime-Auneau submitted a review, later dismissed

2021-02-02 14:43 UTC, Mgaren approved these changes

2021-02-02 14:51 UTC, RomainClair approved these changes

2021-02-02 14:51 UTC, merged