Caterer Page skeleton with some style
WildCodeSchool/tours-php-2009-project3-taste pull request #4
Opened 2020-12-16 11:30 UTC by Maxime-Auneau

2020-12-16 11:33 UTC, axelhamil approved these changes, later dismissed

2020-12-16 11:34 UTC, axelhamil approved these changes, later dismissed

2020-12-16 11:38 UTC, emrecaydin approved these changes, later dismissed
ok ok

2020-12-16 11:38 UTC, emrecaydin commented on assets/styles/app.scss
>      box-sizing: border-box;
ok

2020-12-16 11:38 UTC, emrecaydin commented on config/packages/twig.yaml
> +    form_themes: ['bootstrap_4_layout.html.twig']
ok

2020-12-16 11:38 UTC, emrecaydin commented on package.json
>      "private": true,
ok

2020-12-16 11:38 UTC, emrecaydin commented on package.json
>  }
ok

2020-12-16 11:38 UTC, emrecaydin commented on public/style/catererstyle.css
> +}
ok

2020-12-16 11:38 UTC, emrecaydin commented on src/Controller/CatererController.php
> +}
ok

2020-12-16 11:38 UTC, emrecaydin commented on src/Entity/Caterer.php
> +}
ok

2020-12-16 11:38 UTC, emrecaydin commented on src/Form/CatererType.php
> +}
ok

2020-12-16 11:38 UTC, emrecaydin commented on src/Repository/CatererRepository.php
> +}
ok

2020-12-16 11:38 UTC, emrecaydin commented on templates/base.html.twig
>      {% endblock %}
ok

2020-12-16 11:38 UTC, emrecaydin commented on templates/base.html.twig
>      <body>
ok

2020-12-16 11:38 UTC, emrecaydin commented on templates/base.html.twig
>      </body>
ok

2020-12-16 11:38 UTC, emrecaydin commented on templates/caterer/caterer.html.twig
> +{% endblock %}
ok

2020-12-16 11:38 UTC, emrecaydin commented on templates/caterer/layout.html.twig
> +{% endblock %}
ok

2020-12-16 11:38 UTC, emrecaydin commented on yarn.lock
>    resolved "https://registry.yarnpkg.com/brace-expansion/-/brace-expansion-1.1.11.tgz#3c7fcbf529d87226f3d2f52b966ff5271eb441dd"
ok

2020-12-16 12:08 UTC, axelhamil submitted a review, later dismissed

2020-12-16 12:26 UTC, leobro7 approved these changes, later dismissed
ok

2020-12-18 13:50 UTC, leobro7 submitted a review, later dismissed

2020-12-18 13:54 UTC, axelhamil approved these changes, later dismissed

2020-12-18 13:54 UTC, leobro7 approved these changes, later dismissed

2020-12-21 08:14 UTC, RomainClair requested changes
The Caterer entity lack the constraints for the validation process

2020-12-21 08:14 UTC, RomainClair commented on src/Entity/Caterer.php
> +    private string $date;
This should probably be a date

2020-12-21 08:14 UTC, RomainClair commented on src/Controller/CatererController.php
> +        if ($form->isSubmitted()) {
You should also validate you form, not only check for submission

2021-01-06 10:20 UTC, axelhamil submitted a review, later dismissed

2021-01-06 10:23 UTC, leobro7 approved these changes, later dismissed

2021-01-06 12:44 UTC, RomainClair requested changes
The validator doesn't have any constraints to work with. You should add them in the Caterer entity

2021-01-06 12:44 UTC, RomainClair commented on src/Controller/CatererController.php
> +            $entityManager = $this->getDoctrine()->getManager();
You should use the dependency injection instead

2021-01-07 09:40 UTC, axelhamil approved these changes

2021-01-07 09:40 UTC, leobro7 approved these changes

2021-01-07 09:40 UTC, Mgaren approved these changes

2021-01-07 10:59 UTC, RomainClair approved these changes

2021-01-07 10:59 UTC, RomainClair commented on src/Entity/Caterer.php
> +     * @Assert\NotBlank(message="Votre ne Email ne peut pas être vide")
May be there's too many "ne"

2021-01-07 11:00 UTC, merged