User admin
WildCodeSchool/tours-php-2009-project3-taste pull request #8
Opened 2021-01-18 09:29 UTC by Mgaren

branch FAQ oublié de changer de branch mais c la user ADMIN

2021-01-18 09:55 UTC, axelhamil approved these changes, later dismissed

2021-01-18 10:00 UTC, axelhamil approved these changes, later dismissed

2021-01-18 10:08 UTC, Maxime-Auneau reviewed
ok

2021-01-19 16:49 UTC, Maxime-Auneau approved these changes, later dismissed
**C'est ok le conflit est résolu**

2021-01-19 18:48 UTC, leobro7 approved these changes, later dismissed

2021-01-20 09:24 UTC, RomainClair requested changes
The migration/Version files are not compatible with the dev branch ones.
The caterer table already exists
You shouldn't have unused or test code in your dev branch

2021-01-20 15:18 UTC, axelhamil approved these changes, later dismissed

2021-01-21 08:22 UTC, RomainClair requested changes
The migration files are still not compatible with  the dev ones.
It is impossible to apply the migrations from this branch on a database in the state it is after applying the migrations on the dev branch

2021-01-21 08:22 UTC, RomainClair commented on src/Controller/SessionController.php
> +}
You should not merge test or incomplete code in the dev branch

2021-01-21 09:49 UTC, leobro7 approved these changes, later dismissed

2021-01-21 10:11 UTC, axelhamil submitted a review, later dismissed
It's ok for me, migrations work on my side

2021-01-21 10:51 UTC, maxime-auneau approved these changes

2021-01-21 10:53 UTC, RomainClair approved these changes

2021-01-21 10:53 UTC, merged